name: SlimefunInputNodeFix
author: Paul1365972
version: 1.2
main: de.paul1365972.slimefunfix.InputNodeFix
depend: [Slimefun, CS-CoreLib]

commands:
  slimefunfix:
    usage: /<command> [force|blacklist]
    description: Fixes Slimefun Chunk in an 10 Block range

permissions:
  slimefunfix.nodes:
    description: Allows you to fix chunks
    default: true